#!/bin/sh

files=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.(ts|js)$")
if [ "$files" = "" ]; then
  exit 0
fi

fail() {
  RED='\033[0;31m'
  ORANGE='\033[0;33m'
  NC='\033[0m' # No Color
  echo ""
  echo "${RED}COMMIT FAILED:${NC}"
  echo ""
  echo "Please ${ORANGE}scroll up${NC} to see the type errors."
  echo "First fix them and then try again."
  exit 1
}

echo "Type checking server code..."
npm run pre-commit || fail
